[project]
name = "{name}"
version = "{version}"
description = "Core package for the ESPU ecosystem"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "EscapedShadows" }
]

dependencies = []

[project.optional-dependencies]
{extras}

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"